# Generated by Django 4.2.18 on 2025-02-03 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_content_post_created_on_post_excerpt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_on',
        ),
    ]
