# Generated by Django 4.2.18 on 2025-02-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_collaboraterequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollaborateRequest',
            new_name='Post_request',
        ),
    ]
